---
version: '2'
services:
  wallet:
    hostname: wallet
    depends_on:
      - db
    ports:
      - 8080:8080
    image: kuehne-nagel/wallet
    environment:
      SPRING_PROFILES_ACTIVE: "docker"

  db:
    hostname: db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
